openapi: 3.0.3
info:
  title: Contare API
  description: A simple contare API
  version: 1.0.0
paths:
  /customer:
    get:
      tags:
        - Customer
      summary: Find customer by ID
      description: Returns a list of customers
      operationId: getCustomerById
      parameters:
        - name: id
          in: query
          required: false
          description: ID of customer
          example: "4e519c68-9562-405d-8254-19c7d2925169"
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomersResponse'
    post:
      tags:
        - Customer
      summary: Add a new customer
      description: Add a new customer
      operationId: addCustomer
      requestBody:
        description: Create a new customer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
    put:
      tags:
        - Customer
      summary: Update an existing customer
      description: Update an existing customer
      operationId: updateCustomer
      requestBody:
        description: Update an existing customer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
    delete:
      tags:
        - Customer
      summary: Delete an existing customer by ID
      description: Delete an existing customer
      operationId: deleteCustomer
      parameters:
        - name: id
          in: query
          required: true
          description: ID of customer
          example: "4e519c68-9562-405d-8254-19c7d2925169"
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Successful operation
  /employer:
    get:
      tags:
        - Employer
      summary: Find employer by ID
      description: Returns a list of employers
      operationId: getEmployerById
      parameters:
        - name: id
          in: query
          required: false
          description: ID of employer
          example: "4e519c68-9562-405d-8254-19c7d2925169"
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployersResponse'
    post:
      tags:
        - Employer
      summary: Add a new employer
      description: Add a new employer
      operationId: addEmployer
      requestBody:
        description: Create a new employer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmployerRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployerResponse'
    put:
      tags:
        - Employer
      summary: Update an existing employer
      description: Update an existing employer
      operationId: updateEmployer
      requestBody:
        description: Update an existing employer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmployerRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployerResponse'
    delete:
      tags:
        - Employer
      summary: Delete an existing employer by ID
      description: Delete an existing employer
      operationId: deleteEmployer
      parameters:
        - name: id
          in: query
          required: true
          description: ID of employer
          example: "4e519c68-9562-405d-8254-19c7d2925169"
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Successful operation
  /product:
    get:
      tags:
        - Product
      summary: Find product by ID
      description: Returns a list of products
      operationId: getProductById
      parameters:
        - name: id
          in: query
          required: false
          description: ID of product
          example: "4e519c68-9562-405d-8254-19c7d2925169"
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
    post:
      tags:
        - Product
      summary: Add a new product
      description: Add a new product
      operationId: addProduct
      requestBody:
        description: Create a new product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
    put:
      tags:
        - Product
      summary: Update an existing product
      description: Update an existing product
      operationId: updateProduct
      requestBody:
        description: Update an existing product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
    delete:
      tags:
        - Product
      summary: Delete an existing product by ID
      description: Delete an existing product
      operationId: deleteProduct
      parameters:
        - name: id
          in: query
          required: true
          description: ID of product
          example: "4e519c68-9562-405d-8254-19c7d2925169"
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Successful operation


components:
  schemas:
    CustomersResponse:
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/customer'
    CustomerResponse:
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/Customer'
    Customer:
      type: object
      required:
        - id
        - firstName
        - lastName
        - phone
        - address
        - email
      properties:
        id:
          type: string
          format: uuid
          description: ID of customer
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Galt
        patronymic:
          type: string
          example: Something's
        phone:
          type: string
          example: +7 999 999 99 99
        address:
          type: string
          example: Al Raha Beach st.
        email:
          type: string
          example: galt@email.com
    CreateCustomerRequest:
      type: object
      required:
        - firstName
        - lastName
        - phone
        - address
        - email
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Galt
        patronymic:
          type: string
        phone:
          type: string
          example: +7 999 999 99 99
        address:
          type: string
          example: Al Raha Beach st.
        email:
          type: string
          example: galt@email.com
    UpdateCustomerRequest:
      type: object
      required:
        - id
        - firstName
        - lastName
        - phone
        - address
        - email
      properties:
        id:
          type: string
          format: uuid
          description: ID of customer
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Galt
        patronymic:
          type: string
        phone:
          type: string
          example: +7 999 999 99 99
        address:
          type: string
          example: Al Raha Beach st.
        email:
          type: string
          example: galt@email.com

    EmployersResponse:
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/employer'
    EmployerResponse:
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/Employer'
    Employer:
      type: object
      required:
        - id
        - firstName
        - lastName
        - phone
        - address
        - email
      properties:
        id:
          type: string
          format: uuid
          description: ID of employer
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Galt
        patronymic:
          type: string
          example: Something's
        phone:
          type: string
          example: +7 999 999 99 99
        address:
          type: string
          example: Al Raha Beach st.
        email:
          type: string
          example: galt@email.com
    CreateEmployerRequest:
      type: object
      required:
        - firstName
        - lastName
        - phone
        - address
        - email
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Galt
        patronymic:
          type: string
        phone:
          type: string
          example: +7 999 999 99 99
        address:
          type: string
          example: Al Raha Beach st.
        email:
          type: string
          example: galt@email.com
    UpdateEmployerRequest:
      type: object
      required:
        - id
        - firstName
        - lastName
        - phone
        - address
        - email
      properties:
        id:
          type: string
          format: uuid
          description: ID of employer
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Galt
        patronymic:
          type: string
        phone:
          type: string
          example: +7 999 999 99 99
        address:
          type: string
          example: Al Raha Beach st.
        email:
          type: string
          example: galt@email.com

    ProductsResponse:
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/product'
    ProductResponse:
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/product'
    Product:
      type: object
      required:
        - id
        - name
        - description
        - price
      properties:
        id:
          type: string
          format: uuid
          description: ID of product
        name:
          type: string
          example: Oil change
        description:
          type: string
          example: Remove the old oil and full a new one
        price:
          type: string
          example: 300
    CreateProductRequest:
      type: object
      required:
        - name
        - description
        - price
      properties:
        name:
          type: string
          example: Oil change
        description:
          type: string
          example: Remove the old oil and full a new one
        price:
          type: string
          example: 300
    UpdateProductRequest:
      type: object
      required:
        - id
        - name
        - description
        - price
      properties:
        id:
          type: string
          format: uuid
          description: ID of product
        name:
          type: string
          example: Oil change
        description:
          type: string
          example: Remove the old oil and full a new one
        price:
          type: string
          example: 300